apiVersion: 1

datasources:
  # Tempo - trace queries
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: tempo
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: tempo

  # Prometheus - metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    uid: prometheus
    jsonData:
      httpMethod: POST